name: muscule_test
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  auto_size_text: ^2.1.0
  percent_indicator: "^2.1.1"
  admob_flutter: "^0.3.4"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/femi.jpg
    - assets/mask.jpg
    - assets/andro.jpg
    - assets/answers.json

  uses-material-design: true

module:
  andoridX: true